[features]
seeds = false
skip-lint = false
[programs.localnet]
gif_portal = "7eDtFtH92kuc8dwNgAvoL2dKfbVauELpVcSpbWdF4vX4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/mkulima/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
